export const STORE_EXERCISES = 'STORE_EXERCISES';
export const STORE_CURRENT_EXERCISE = 'STORE_CURRENT_EXERCISE';

export const SET_IS_LOADING = 'SET_IS_LOADING';

export const LOCK_SUCCESS = 'LOCK_SUCCESS';
export const LOCK_ERROR = 'LOCK_ERROR';

export const LOGOUT = 'LOGOUT';
